import { StationId } from '@repo/shared/enums';
import { EquipmentAsset } from './types';

export const STATION_EQUIPMENT: Record<StationId, EquipmentAsset[]> = {
  [StationId.MAITRI]: [
    {
      assetId: 'GEN-002',
      stationId: StationId.MAITRI,
      name: 'Main Generator Unit 02',
      category: 'ENERGY',
      subType: 'DIESEL_GENSET',
      status: 'CRITICAL',
      healthIndex: 42.5,
      metrics: {
        operatingTemperatureC: 97.4,
        powerOutputKw: 184.0,
        fuelConsumptionLph: 8.2,
        vibrationRms: 4.8,
        operatingHours: 4120,
      },
      spatial: {
        position: [14.2, 1.0, -8.5],
        rotation: [0.0, 1.57, 0.0],
        boundingZone: 'POWER_HOUSE_ZONE_A',
      },
      prediction: {
        failureProbability72h: 0.78,
        estimatedTimeToFailureHours: 14.5,
        recommendedAction: 'Shed non-critical lab heating to reduce genset load below 70%',
      },
      lastUpdated: '2026-09-09T16:45:00Z',
    },
    {
      assetId: 'GEN-001',
      stationId: StationId.MAITRI,
      name: 'Main Generator Unit 01',
      category: 'ENERGY',
      subType: 'DIESEL_GENSET',
      status: 'NORMAL',
      healthIndex: 91.0,
      metrics: {
        operatingTemperatureC: 82.1,
        powerOutputKw: 160.0,
        fuelConsumptionLph: 7.1,
        vibrationRms: 1.6,
        operatingHours: 2980,
      },
      spatial: {
        position: [9.5, 1.0, -8.5],
        rotation: [0.0, 1.57, 0.0],
        boundingZone: 'POWER_HOUSE_ZONE_A',
      },
      prediction: {
        failureProbability72h: 0.04,
        estimatedTimeToFailureHours: 620.0,
        recommendedAction: 'Nominal operation. Next scheduled maintenance in 140 operating hours.',
      },
      lastUpdated: '2026-09-09T17:10:00Z',
    },
    {
      assetId: 'WTR-001',
      stationId: StationId.MAITRI,
      name: 'Lake Priyadarshini Water Intake System',
      category: 'INFRASTRUCTURE',
      subType: 'PUMP_HEAT_TRACE',
      status: 'WARNING',
      healthIndex: 64.2,
      metrics: {
        operatingTemperatureC: 1.8,
        differentialPressurePsi: 28.5,
        operatingHours: 8750,
      },
      spatial: {
        position: [-32.0, 0.2, 45.1],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'PRIYADARSHINI_PUMP_STATION',
      },
      prediction: {
        failureProbability72h: 0.42,
        estimatedTimeToFailureHours: 48.0,
        recommendedAction: 'Activate secondary auxiliary trace heating circuit on intake line 2.',
      },
      lastUpdated: '2026-09-09T17:05:00Z',
    },
    {
      assetId: 'HVAC-001',
      stationId: StationId.MAITRI,
      name: 'Main Habitat Air Circulation Unit',
      category: 'ENVIRONMENT',
      subType: 'HVAC_CORE',
      status: 'NORMAL',
      healthIndex: 88.4,
      metrics: {
        operatingTemperatureC: 21.5,
        humidityPct: 34.0,
        differentialPressurePsi: 1.2,
        operatingHours: 5400,
      },
      spatial: {
        position: [0.0, 3.5, 0.0],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'MAIN_HABITAT_PLENUM',
      },
      prediction: {
        failureProbability72h: 0.08,
        estimatedTimeToFailureHours: 420.0,
        recommendedAction: 'Inspect HEPA intake pre-filters after upcoming gale subsidence.',
      },
      lastUpdated: '2026-09-09T17:15:00Z',
    },
    {
      assetId: 'SAT-001',
      stationId: StationId.MAITRI,
      name: 'ISRO Ku-Band 3.8m Tracking Dish',
      category: 'CONNECTIVITY',
      subType: 'EARTH_STATION_ANTENNA',
      status: 'NORMAL',
      healthIndex: 94.0,
      metrics: {
        rxSnrDb: 14.8,
        operatingHours: 12200,
      },
      spatial: {
        position: [28.4, 4.2, 12.0],
        rotation: [0.2, 0.8, 0.0],
        boundingZone: 'TELECOM_RADOME_NORTH',
      },
      prediction: {
        failureProbability72h: 0.02,
        estimatedTimeToFailureHours: 890.0,
        recommendedAction: 'Link margin nominal. Radome heater auto-cycling active.',
      },
      lastUpdated: '2026-09-09T17:12:00Z',
    },
    {
      assetId: 'FUEL-003',
      stationId: StationId.MAITRI,
      name: 'Aviation Turbine Fuel Tank Farm 03',
      category: 'LOGISTICS',
      subType: 'CRYOGENIC_FUEL_STORAGE',
      status: 'NORMAL',
      healthIndex: 86.5,
      metrics: {
        tankLevelPct: 78.4,
        operatingTemperatureC: -14.2,
        operatingHours: 9200,
      },
      spatial: {
        position: [-18.5, 0.5, -28.0],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'POL_TANK_FARM_SOUTH',
      },
      prediction: {
        failureProbability72h: 0.05,
        estimatedTimeToFailureHours: 720.0,
        recommendedAction: 'Reserve adequate for 94 days at current burn rates.',
      },
      lastUpdated: '2026-09-09T16:50:00Z',
    },
    {
      assetId: 'BAT-001',
      stationId: StationId.MAITRI,
      name: 'Emergency Backup Battery Bank Alpha',
      category: 'ENERGY',
      subType: 'BATTERY_BESS',
      status: 'NORMAL',
      healthIndex: 91.5,
      metrics: {
        tankLevelPct: 92.0,
        operatingTemperatureC: 19.5,
        powerOutputKw: 38.0,
        operatingHours: 3400,
      },
      spatial: {
        position: [11.8, 1.0, -9.8],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'POWER_HOUSE_ZONE_B',
      },
      prediction: {
        failureProbability72h: 0.04,
        estimatedTimeToFailureHours: 850.0,
        recommendedAction: 'Float charge stable at 54.2V. Thermal stabilization nominal.',
      },
      lastUpdated: '2026-09-09T17:15:00Z',
    },
    {
      assetId: 'DEPOT-001',
      stationId: StationId.MAITRI,
      name: 'PistenBully Snowcat & Heavy Sledge Bay',
      category: 'LOGISTICS',
      subType: 'OVERLAND_FLEET',
      status: 'NORMAL',
      healthIndex: 87.0,
      metrics: {
        tankLevelPct: 85.0,
        operatingTemperatureC: -8.0,
        operatingHours: 2150,
      },
      spatial: {
        position: [15.0, 0.5, 16.0],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'LOGISTICS_DEPOT_EAST',
      },
      prediction: {
        failureProbability72h: 0.07,
        estimatedTimeToFailureHours: 540.0,
        recommendedAction: 'Pre-heat block engine heaters engaged for convoy mission.',
      },
      lastUpdated: '2026-09-09T17:00:00Z',
    },
  ],
  [StationId.BHARATI]: [
    {
      assetId: 'GEN-B01',
      stationId: StationId.BHARATI,
      name: 'Modular Cogeneration Genset 01',
      category: 'ENERGY',
      subType: 'CHP_DIESEL_GENSET',
      status: 'NORMAL',
      healthIndex: 92.5,
      metrics: {
        operatingTemperatureC: 84.0,
        powerOutputKw: 220.0,
        fuelConsumptionLph: 9.4,
        vibrationRms: 1.8,
        operatingHours: 1950,
      },
      spatial: {
        position: [12.0, 0.8, -6.0],
        rotation: [0.0, 3.14, 0.0],
        boundingZone: 'BHARATI_ENERGY_POD_1',
      },
      prediction: {
        failureProbability72h: 0.03,
        estimatedTimeToFailureHours: 950.0,
        recommendedAction: 'Heat recovery loop operating at 94% thermal efficiency.',
      },
      lastUpdated: '2026-09-09T17:10:00Z',
    },
    {
      assetId: 'SAT-B01',
      stationId: StationId.BHARATI,
      name: 'NRSC Remote Sensing Direct Reception X-Band Antenna',
      category: 'CONNECTIVITY',
      subType: 'HIGH_RATE_SATELLITE_DOWNLINK',
      status: 'CRITICAL',
      healthIndex: 38.0,
      metrics: {
        operatingTemperatureC: -28.4,
        rxSnrDb: 6.2,
        operatingHours: 8400,
      },
      spatial: {
        position: [24.0, 8.5, 18.0],
        rotation: [0.4, 1.2, 0.0],
        boundingZone: 'RADOME_ALPHA',
      },
      prediction: {
        failureProbability72h: 0.84,
        estimatedTimeToFailureHours: 9.0,
        recommendedAction: 'Azimuth drive feedback encoder signal dropout. Switch to backup antenna for upcoming Cartosat pass.',
      },
      lastUpdated: '2026-09-09T17:18:00Z',
    },
    {
      assetId: 'RO-B01',
      stationId: StationId.BHARATI,
      name: 'Seawater Desalination RO Train 01',
      category: 'INFRASTRUCTURE',
      subType: 'REVERSE_OSMOSIS_DESAL',
      status: 'NORMAL',
      healthIndex: 89.0,
      metrics: {
        differentialPressurePsi: 58.2,
        operatingTemperatureC: 4.2,
        operatingHours: 3200,
      },
      spatial: {
        position: [-14.0, 0.0, 22.0],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'WATER_PLANT_POD',
      },
      prediction: {
        failureProbability72h: 0.06,
        estimatedTimeToFailureHours: 580.0,
        recommendedAction: 'Permeate TDS at 85 ppm. Optimal salinity rejection.',
      },
      lastUpdated: '2026-09-09T17:00:00Z',
    },
    {
      assetId: 'HVAC-B02',
      stationId: StationId.BHARATI,
      name: 'Habitat Lab Zone Air Balancing Damper',
      category: 'ENVIRONMENT',
      subType: 'VAV_PRESSURIZED_DAMPER',
      status: 'WARNING',
      healthIndex: 68.0,
      metrics: {
        operatingTemperatureC: 18.9,
        differentialPressurePsi: 3.4,
        humidityPct: 29.5,
        operatingHours: 4100,
      },
      spatial: {
        position: [2.5, 4.0, 8.0],
        rotation: [0.0, 1.57, 0.0],
        boundingZone: 'HABITAT_CORE_LEVEL_2',
      },
      prediction: {
        failureProbability72h: 0.38,
        estimatedTimeToFailureHours: 36.0,
        recommendedAction: 'Recalibrate differential pressure transducer across cleanroom airlock.',
      },
      lastUpdated: '2026-09-09T17:14:00Z',
    },
    {
      assetId: 'BAT-B01',
      stationId: StationId.BHARATI,
      name: 'Peak Shaving Battery Energy Storage (LTO)',
      category: 'ENERGY',
      subType: 'BATTERY_BESS',
      status: 'NORMAL',
      healthIndex: 96.0,
      metrics: {
        tankLevelPct: 88.0,
        operatingTemperatureC: 22.1,
        powerOutputKw: 45.0,
        operatingHours: 1820,
      },
      spatial: {
        position: [16.5, 0.8, -6.0],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'BHARATI_ENERGY_POD_2',
      },
      prediction: {
        failureProbability72h: 0.01,
        estimatedTimeToFailureHours: 1200.0,
        recommendedAction: 'BESS State of Health 98.4%. Peak shaving operating smoothly.',
      },
      lastUpdated: '2026-09-09T17:12:00Z',
    },
    {
      assetId: 'FUEL-B01',
      stationId: StationId.BHARATI,
      name: 'Polar Diesel Fuel Tank Bulk Storage',
      category: 'LOGISTICS',
      subType: 'CRYOGENIC_FUEL_STORAGE',
      status: 'NORMAL',
      healthIndex: 91.0,
      metrics: {
        tankLevelPct: 82.5,
        operatingTemperatureC: -16.0,
        operatingHours: 4800,
      },
      spatial: {
        position: [-10.0, 0.5, -20.0],
        rotation: [0.0, 0.0, 0.0],
        boundingZone: 'BHARATI_POL_DEPOT',
      },
      prediction: {
        failureProbability72h: 0.03,
        estimatedTimeToFailureHours: 880.0,
        recommendedAction: 'Fuel quality nominal. Zero water bottom condensation detected.',
      },
      lastUpdated: '2026-09-09T17:08:00Z',
    },
  ],
};

export function getStationEquipment(stationId: StationId): EquipmentAsset[] {
  return STATION_EQUIPMENT[stationId] || STATION_EQUIPMENT[StationId.MAITRI];
}
